const locationImages = {
  1: "/images/safari-park.png",
  2: "/images/seaport-village.png",
  3: "/images/comic-con.png",
  4: "/images/stone-brewery.png",
  5: "/images/cafe-21.png",
  6: "/images/surfari-surf-lesson.png",
  7: "/images/torrey-pines.png",
  8: "/images/gaslamp-ghost-tour.png",
  9: "/images/birch-aquarium.png",
  10: "/images/museum-of-man.png",
  11: "/images/adams-bookstore.png",
  12: "/images/crazee-burger.png",
  13: "/images/convoy-district.png",
  14: "/images/agua-caliente-hot-springs.png",
  15: "/images/thrift-trader.png",
  16: "/images/fashion-valley.png",
  17: "/images/farmers-market.png",
  18: "/images/scuba.png",
  19: "/images/casbah-concert.png",
  20: "/images/legoland.png",
  21: "/images/central-library.png",
  22: "/images/old-globe-theatre.png",
  23: "/images/organ-pavilion.png",
  24: "/images/mission-beach-boardwalk.png",
  25: "/images/drive-in-theatre.png",
  26: "/images/ninja-night-race.png",
  27: "/images/blacks-beach.png",
  28: "/images/barrio-logan.png",
  29: "/images/extraordinary-desserts.png",
  30: "/images/hash-house-a-go-go.png"
};

export default locationImages;
